# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94879d07cef16b6057aeba7502df255eb757c68c9837acc74c7cf567ea277da021f9d1e3cb15e74e1839b84dc77a9c697760bf6b3a154466737560a9517dcb03

test:
  secret_key_base: ea85dcf6f17c07934d740369feabd55d1215f0004021fd564f507375f6981308f72d617ec7e5e5fa2fd001c45873fb7f8cecf884d3e4e4784f0b27164f0a7ffb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
